# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

a1 = Activity.create(name:'swimming', description: "Swimming is a low-impact cardiovascular exercise that provides a full-body workout. It's an excellent activity for building endurance, toning muscles, and improving overall fitness. When you swim, you work your arms, legs, and core, and you can do so at your own pace. Whether you're doing laps in a pool or swimming in open water, this activity is great for people of all ages and fitness levels.", image: 'swimming.jpg')
a2 = Activity.create(name:'running', description: "Running is a high-impact aerobic exercise that's great for improving cardiovascular fitness, burning calories, and improving your mood. It's an activity that you can do almost anywhere, from a treadmill at the gym to your local park or neighborhood. Running is a great way to challenge yourself and build endurance, and it can be a social activity too if you join a running club or participate in races.", image: 'running.jpg')
a3 = Activity.create(name:'cycling', description: "Cycling is a low-impact aerobic exercise that's great for building cardiovascular endurance, leg strength, and core stability. Whether you're riding a stationary bike in the gym or hitting the road on a bicycle, cycling is a fun and effective way to improve your fitness. It's also a great activity for exploring your community or the great outdoors, and it can be a social activity if you ride with friends or join a cycling club.", image: 'cycling.jpg')
a4 = Activity.create(name:'hiking', description: "Hiking is a moderate-to-high intensity activity that gets you outdoors and can improve your cardiovascular fitness, build lower body strength, and boost your mood. Whether you're hiking on a mountain trail or walking in a local park, this activity is great for getting some fresh air and exercise. It's also a great way to explore your surroundings and connect with nature.", image: 'hiking.jpg')
a5 = Activity.create(name:'yoga', description: "Yoga is a low-impact exercise that improves flexibility, balance, and strength, as well as reducing stress and anxiety. It's an activity that you can do almost anywhere, from a yoga studio to your living room. There are many different types of yoga, from gentle and restorative to intense and challenging, so you can find a style that suits your needs and fitness level.", image: 'yoga.jpg')
a6 = Activity.create(name:'dancing', description: "Dancing is a fun way to improve cardiovascular fitness, coordination, and balance, as well as reducing stress and boosting your mood. There are many different types of dance, from salsa and tango to hip-hop and ballet, so you can find a style that you enjoy and that suits your fitness level. Dancing can be a social activity too, so it's a great way to meet new people and have fun.", image: 'dancing.jpg')
a7 = Activity.create(name:'gym workout', description: " A gym workout is a strength training routine that can help build muscle, burn fat, and improve overall health and fitness. Whether you're lifting weights or using resistance machines, a gym workout can be a great way to challenge yourself and improve your strength and endurance. It's also a great activity for people who enjoy working out indoors and who want to have access to a variety of equipment.", image: 'gymworkout.jpg')
a8 = Activity.create(name:'basketball', description: "Basketball is a high-intensity sport that can improve your cardiovascular fitness, agility, coordination, and teamwork skills. Whether you're playing on a team or just shooting hoops by yourself, basketball is a fun and challenging activity that can help you improve your physical fitness and social skills. It's also a great way to connect with others and have fun.", image: 'basketball.jpg')
a9 = Activity.create(name:'soccer', description: "Soccer is a team sport that's great for building cardiovascular endurance, lower body strength, and teamwork skills. Whether you're playing in a league or just kicking a ball around with friends, soccer is a fun and challenging activity that can help you improve your physical fitness and social skills. It's also a great way to meet new people and have fun.", image: 'soccer.jpg')
a10 = Activity.create(name:'volleyball', description: "Volleyball is a fun and exciting team sport that can be played both indoors and outdoors. It involves two teams of six players each, who try to score points by hitting a ball over a high net and onto the opponent's side of the court without the other team being able to return it. Volleyball is a great way to improve your coordination, agility, and teamwork skills, as well as get a full-body workout. Whether you're playing with friends or in a competitive league, volleyball is a sport that can be enjoyed by people of all ages and skill levels.", image: 'volleyball.jpg')

